// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvjjCMHrirIr0m5PQtx_ZJvuGFS3OAiBA',
    appId: '1:695581330081:web:c49abba0613fbce8e3bee0',
    messagingSenderId: '695581330081',
    projectId: 'emvibe-eba0b',
    authDomain: 'emvibe-eba0b.firebaseapp.com',
    storageBucket: 'emvibe-eba0b.firebasestorage.app',
    measurementId: 'G-WCCVE9BRB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOg7g6ddPAicelGoC8lp0FpcnWYPVTo_Q',
    appId: '1:695581330081:android:55976cd724bab723e3bee0',
    messagingSenderId: '695581330081',
    projectId: 'emvibe-eba0b',
    storageBucket: 'emvibe-eba0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMCzfNO-D35iu1EbU-KzrSyNMp03Pz3s8',
    appId: '1:695581330081:ios:cd042958fa2de397e3bee0',
    messagingSenderId: '695581330081',
    projectId: 'emvibe-eba0b',
    storageBucket: 'emvibe-eba0b.firebasestorage.app',
    androidClientId: '695581330081-l50jef71aeu7fua300mmlvp4n2e2egpa.apps.googleusercontent.com',
    iosClientId: '695581330081-g5b91ljrdfuo6safm6dg6oe2js6d2ttg.apps.googleusercontent.com',
    iosBundleId: 'com.example.emvibe',
  );
}
